hydra:
  run:
    dir: runs/${MODEL_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S} #runs/RBC/2024-11-17/07-51-09
    #dir: 
    #dir: ../../../../OUTPUT_HYDRA/${MODEL_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
defaults:
  - constants: RBC
  - net: RBC
  - optimizer: RBC
  - run: RBC
  - variables: RBC
seed: 42 #42
# can be NEW, LATEST, or a given checkpoint filename
STARTING_POINT: LATEST
CHECKPOINT_INTERVAL: 2
MAX_TO_KEEP_NUMBER: 10
MODEL_NAME: RBC
#False-> Simulation; True -> draw
initialize_each_episode: True
error_filename: error_file.txt
enable_check_numerics: False