# State variables
states:
  # Endogenous state variables:
  - name: lKt  # Capital stock in period t in logs
    init:
      distribution: truncated_normal
      kwargs:
        mean: 2.90
        stddev: 0.0 
        # For deterministic model: add a distribution and standard deviation such that simulation are stochastic

  # Exogenous state variables:
  - name: lZt  # TFP in logs
    init:
      distribution: truncated_normal
      kwargs:
        mean: 0.
        stddev: 0.

policies:
  - name: lCt  # Consumption in logs


definitions:
  - name: get_lKn #capital next period (in logs)
  - name: get_RHSt # "right-hand-side of Euler (but in period t!)
  - name: get_Kt  #take exponent of lKt
  - name: get_Zt  #take exponent lZt
  - name: get_Ct  #take exponent lCt
  - name: get_Ht # Labour supply
  - name: marg_ut # marginal utility
  - name: Y_t  # Output
  - name: R_t # Marg. productivity of capital
  - name: get_ss #get steady state


