# State variables
states:
  # Endogenous state variables:
  - name: lKt  # Capital stock in period t in logs
    init:
      distribution: truncated_normal
      kwargs:
        mean: 2.90
        stddev: 0.0 
        # For deterministic model: add a distribution and standard deviation such that simulation are stochastic

  # Exogenous state variables:
  - name: lZt  # TFP in logs
    init:
      distribution: truncated_normal
      kwargs:
        mean: 0.
        stddev: 0.

policies:
  - name: st   # savings rate
  - name: lHt  # Hours worked in logs


definitions:
  - name: get_Kt  # exponent of lKt
  - name: get_Zt  # exponent lZt
  - name: get_Ht  # exponent lHt
  - name: get_lKn #capital next period (in logs)
  - name: get_RHSt # "right-hand-side of Euler (but in period t!)
  - name: get_Ct # consumption
  - name: get_marg_ut # marginal utility of consumption
  - name: get_Yt  # Output
  - name: get_Rt # Marg. productivity of capital



